categories:
  - name: default
    model: openai/gpt-4o-mini
    description: >
      For everyday, relatively simple requests with short to medium length (1–3 paragraphs).
      Covers small talk, short explanations, summaries, or general questions
      that do not require deep technical or logical reasoning. Goal: fast and cost-effective answers.

  - name: coding
    model: openai/gpt-4o-mini
    description: >
      For technical requests related to programming, debugging, architecture, or IT tools.
      Includes code snippets, error messages, best practices, and in-depth technical explanations.
      Typically medium length (multiple paragraphs or code blocks) and requires technical expertise.

  - name: deep-reasoning
    model: openai/gpt-4o
    description: >
      For complex, multi-layered tasks requiring high accuracy, creative solutions, or multimodality
      (e.g. images). Best suited for prompts with longer text (several paragraphs to full pages) or
      high logical complexity. Goal: precise, high-quality answers even for difficult problems.

  - name: structured-analysis
    model: anthropic/claude-4-sonnet
    description: >
      For tasks that need detailed, well-structured, text-heavy explanations.
      Particularly useful for longer documents, strategic analyses, or conceptual requests
      where clarity, structure, and deep text understanding are essential.
      Length: multiple paragraphs up to entire documents.

  - name: vision
    model: mistral/pixtral-large-2502
    description: >
      For requests involving images or visual content – such as image description, visual analysis,
      diagram interpretation, or multimodal tasks. Typically indicated by words like "image", "photo",
      "screenshot", or when an image is attached to the prompt.
